system: "You are a helpful AI assistant. Your task is to provide API recommendations to users. Always answer with a syntactically correct API command, and use the API documentation provided as reference."
user: f"Background:\n{docs}\n\nQuestion:\ {question}"
system_without_docs: "You are a helpful AI assistant. Your task is to provide API recommendations to users. Always answer with a syntactically correct API command."
user_without_docs: f"Question:\ {question}"