init_args: 
  _target_: models.generators.llm.LLM
  model_name: "experiments/FT/FT_multiqa_rf_short_gemma2bit_lora_splade_deberta_basicprompt_04epoch/train/checkpoint-11212"
  max_new_tokens: 128
  max_length: 2048
  quantization: "int4"
  batch_size: 8
  local_path: True