# main_config.yaml

defaults:
    - _self_
    - retriever: null
    - reranker: null
    - generator: null
    - dataset: ??
    - train: null
    - prompt: coderagbench_humaneval
    # - query_generator: null  # comment if don't want search query

# main variables locating the local data folder and index
run_name: null
dataset_folder: 'datasets/'
index_folder: 'indexes/'
runs_folder: 'runs/'
generated_query_folder: 'generated_queries/'
processed_context_folder: 'processed_contexts/'
experiments_folder: 'experiments/'    

# topk documents to retrieve, rerank and to use for generation
retrieve_top_k: 25
rerank_top_k: 25
generation_top_k: 5


#
pyserini_num_threads: 20
processing_num_proc: 40
hydra:
    job:
        chdir: False