# main_config.yaml

defaults:
    - _self_
    - retriever: null
    - reranker: null
    - generator: null
    - dataset: ??
    - train: null
    - prompt: basic
    
retrieve_top_k: 50
rerank_top_k: 50
generation_top_k: 5
pyserini_num_threads: 20
run_name: null
dataset_folder: 'datasets/'
index_folder: 'indexes/'
runs_folder: 'runs/'
generated_query_folder: 'generated_queries'
experiments_folder: 'experiments/'
processing_num_proc: 40
hydra:
    job:
        chdir: False
