train:
    doc: 
        init_args:
            _target_: modules.dataset_processor.ODQAWikiCorpora63tamberALL
            split: "train"
    query: 
        init_args:
            _target_: modules.dataset_processor.TimeSensitiveQA
            split: "train"
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.ODQAWikiCorpora63tamberALL
            split: "train"
    query: 
        init_args:
            _target_: modules.dataset_processor.TimeSensitiveQA
            split: "validation"
test:
    doc: 
        init_args:
            _target_: modules.dataset_processor.ODQAWikiCorpora63tamberALL
            split: "train"
    query: 
        init_args:
            _target_: modules.dataset_processor.TimeSensitiveQA
            split: "test"